name = "ScikitLearn"
uuid = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
version = "0.5.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GaussianMixtures = "cc18c42c-b769-54ff-9e2a-b28141a64aae"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScikitLearnBase = "6e75b9c4-186b-50bd-896f-2d2496a4843e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = ">= 0.11"
MacroTools = ">= 0.3"
Parameters = ">= 0.3"
PyCall = "1.91.4"
ScikitLearnBase = ">= 0.0.6"
StatsBase = ">= 0.8"
julia = "â‰¥ 0.7.0"
Compat = "2.1.0"
Conda = "1.4.1"
DecisionTree = "0.10.0"
GaussianMixtures = "0.3.0"
GaussianProcesses = "0.11.2"
IterTools = "1.3.0"
NBInclude = "2.1.0"
PyPlot = "2.8.2"
RData = "0.7"
RDatasets = "0.6"



[extras]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Statistics", "Test"]
